category_profession = {
    'INGENIERO': 'University Education',
    'TECNICO': 'Technical Education',
    'INGENIERO DE MINAS': 'University Education',
    'TEC MECANICO AUTOMOTRIZ': 'Technical Education',
    'ADMINISTRADOR': 'University Education',
    'ECONOMISTA': 'University Education',
    'MIEMBRO DE LAS FUERZAS ARMADAS': 'Skilled Trades',
    'CONTADOR': 'University Education',
    'ARQUITECTO': 'University Education',
    'ENFERMERO': 'Technical Education',
    'INGENIERO QUIMICO': 'University Education',
    'SECRETARIA': 'Skilled Trades',
    'OBRERO / OPERADOR': 'Skilled Trades',
    'MEDICO': 'University Education',
    'MECANICO': 'Skilled Trades',
    'PROFESOR': 'University Education',
    'TECNICO EN ELECTRONICA': 'Technical Education',
    'INGENIERO ELECTRONICO': 'University Education',
    'INGENIERO CIVIL': 'University Education',
    'CIRUJANOS': 'University Education',
    'TEC MECANICO INDUSTRIAL': 'Technical Education',
    'PSICOLOGO/ TERAPEUTA': 'University Education',
    'INGENIERO TEXTIL': 'University Education',
    'EDUCADOR': 'University Education',
    'INGENIERO ELECTRICISTA': 'University Education',
    'ASISTENTE SOCIAL': 'Skilled Trades',
    'PUBLICISTA': 'University Education',
    'TEC ELECTRICIDAD INDUST': 'Technical Education',
    'VARIOS': 'Unknown',
    'ABOGADO': 'University Education',
    'VETERINARIO': 'University Education',
    'INGENIERO DE SISTEMAS': 'University Education',
    'CONDUCTOR': 'Skilled Trades',
    'INGENIERO INDUSTRIAL': 'University Education',
    'RELACIONISTA PUBLICO E INDUSTRIAL': 'University Education',
    'DENTISTA / ODONTOLOGO': 'University Education',
    'PERIODISTA': 'University Education',
    'TOPOGRAFO': 'Technical Education',
    'QUIMICO FARMACEUTICO': 'University Education',
    'NO DIO INFORMACION SOLICITADA': 'Unknown',
    'INGENIERO MECANICO': 'University Education',
    'TECNICO EN CONSTRUCCION': 'Technical Education',
    'OFICIAL FF.AA.': 'Skilled Trades',
    'ELECTRICISTA': 'Skilled Trades',
    'TECNICO MATRICERIA': 'Technical Education',
    'PROFESOR UNIVERSITARIO': 'University Education',
    'ESTUDIANTE': 'Unknown',
    'EMPLEADO FISCAL': 'Skilled Trades',
    'TECNICO EN COMPUTACION': 'Technical Education',
    'TEC ADMINIST.EMPRESAS': 'Technical Education',
    'PROFESOR EDUC BASICA': 'University Education',
    'INGENIERO AGRONOMO': 'University Education',
    'TECNICO CONTROL CALIDAD': 'Technical Education',
    'TEC QUIMICO LAB.INDUST': 'Technical Education',
    'GEOLOGO': 'University Education',
    'TEC ADMINIST INVENTARIOS': 'Technical Education',
    'SOCIOLOGO': 'University Education',
    'AGENTE DE TURISMO/VIAJES': 'Skilled Trades',
    'TECNICO EN ARQUITECTURA': 'Technical Education',
    'SUBOFICIAL POLICIA NACIONAL': 'Skilled Trades',
    'DEPORTISTA PROFESIONAL': 'Skilled Trades',
    'TECNICO AGRICOLA': 'Technical Education',
    'OBSTETRIZ': 'Technical Education',
    'LABORATORISTA': 'Technical Education',
    'OPERADOR DE MAQUINARIA': 'Skilled Trades',
    'INGENIERO COMERCIAL': 'University Education',
    'DISENADOR GRAFICO': 'University Education',
    'ANTROPOLOGO': 'University Education',
    'INGENIERO GEOLOGO': 'University Education',
    'OFICIAL POLICIA NACIONAL': 'Skilled Trades',
    'CONTADOR AUDITOR': 'University Education',
    'PROGRAMADOR COMPUTACION': 'Technical Education',
    'COCINERO / CHEF': 'Skilled Trades',
    'BIOLOGO': 'University Education',
    'INGENIERO METALURGICO': 'University Education',
    'JUBILADO': 'Unknown',
    'TEOLOGO': 'University Education',
    'TEC ADMINIST HOTELERA': 'Technical Education',
    'TEC PROGRAMACION COMPUTAD': 'Technical Education',
    'TECNICO EN AUDITORIA': 'Technical Education',
    'INGENIERO PESQUERO': 'University Education',
    'TRANSPORTISTA': 'Skilled Trades',
    'VENDEDOR AMBULANTE': 'Skilled Trades',
    'NUTRICIONISTA': 'University Education',
    'ANALISTAS DE SISTEMA Y COMPUTACION': 'Technical Education',
    'INGENIERO COMPUTACION': 'University Education',
    'TEC BANCARIO Y FINANCIERO': 'Technical Education',
    'AEROMOZO': 'Skilled Trades',
    'TEC EN TELECOMUNIC': 'Technical Education',
    'NOTARIO': 'Skilled Trades',
    'TECNOLOGO MEDICO': 'Technical Education',
    'DISENADOR VESTUARIO': 'University Education',
    'TRADUCTOR / INTERPRETE': 'Skilled Trades',
    'TECNICO COMERCIO EXTERIOR': 'Technical Education',
    'TEC AYUDANTE ENFERMERIA': 'Technical Education',
    'INGENIERO PETROLERO': 'University Education',
    'MAQUINISTA / OPERADOR MAQUINARIA': 'Skilled Trades',
    'PILOTO AVIACION COMERCIAL': 'Skilled Trades',
    'ADUANERO': 'Skilled Trades',
    '999': 'Unknown',
    'VISITADOR MEDICO': 'Skilled Trades',
    'CONSTRUCTOR': 'Skilled Trades',
    'INGENIERO ANALISTA': 'University Education',
    'FOTOGRAFO / OPERADORES CAMARA': 'Skilled Trades',
    'IMPORTADOR / EXPORTADOR': 'Skilled Trades',
    'ACTOR': 'Skilled Trades',
    'AMA DE CASA': 'Unknown',
    'INTERPRETE': 'Skilled Trades',
    'INGENIERO FORESTAL': 'University Education',
    'DIGITADORA': 'Skilled Trades',
    'TECNICO REFRIGERACION': 'Technical Education',
    'LABORATORISTA QUIMICO': 'Technical Education',
    'TECNICO EN TURISMO': 'Technical Education',
    'TEC COMUNIC.AUDIOVISUAL': 'Technical Education',
    'JARDINERO': 'Skilled Trades',
    'TEC ASISTENTE ARQUITECTURA': 'Technical Education',
    'TAQUIGRAFA': 'Skilled Trades',
    'TECNICO EN PESCA': 'Technical Education',
    'TEC DISENO PUBLICITARIO': 'Technical Education',
    'AGRICULTOR': 'Skilled Trades',
    'ALBAÑIL': 'Skilled Trades',
    'BIBLIOTECARIO': 'University Education',
    'COMERCIANTE / VENDEDOR': 'Skilled Trades',
    'INGENIERO NAVAL': 'University Education',
    'PERSONAL DE SEGURIDAD': 'Skilled Trades',
    'TECNICO PECUARIO': 'Technical Education',
    'INGENIERO ECONOMICO': 'University Education',
    'ALMACENAMIENTO/ALMACENERO': 'Skilled Trades',
    'METEREOLOGO': 'University Education',
    'TEC ANALISTA QUIMICO': 'Technical Education',
    'OTROS MEDICINA': 'Technical Education',
    'COSMETOLOGO': 'Technical Education',
    'PROFESOR ENSNZA MEDIA': 'University Education',
    'ARQUEOLOGO': 'University Education',
    'TEC DIBUJOS/PROYECTOS TECNIC': 'Technical Education',
    'SASTRE': 'Skilled Trades',
    'CONFECCIONISTA': 'Skilled Trades',
    'INGENIERO EN SONIDO': 'University Education',
    'OCULISTA': 'Technical Education',
    'METALURGISTA': 'Skilled Trades',
    'COMERCIANTE': 'Skilled Trades',
    'DIBUJANTE TECNICO': 'Technical Education',
    'SUBOFICIAL FF.AA.': 'Skilled Trades',
    'CAPATAZ': 'Skilled Trades',
    'CAJERO': 'Skilled Trades',
    'CARPINTERO': 'Skilled Trades',
    'TECNICO JURIDICO': 'Technical Education',
    'TASADOR': 'Skilled Trades',
    'LOCUTOR DE RADIO Y TV': 'Skilled Trades',
    'OTROS INGENIEROS': 'University Education',
    'DECORADOR INTERIORES': 'Skilled Trades',
    'PELUQUERO': 'Skilled Trades',
    'LICENCIADO EDUCACION': 'University Education',
    'MUSICO': 'Skilled Trades',
    'DIETISTA': 'Technical Education',
    'JOYERO Y/O PLATERO / ORFEBRE': 'Skilled Trades',
    'POLICIA MUNICIPAL': 'Skilled Trades',
    'TRAMITADOR': 'Skilled Trades',
    'RETOCADOR': 'Skilled Trades',
    'TRANSPORTE DE CARGA Y/O MUDANZA': 'Skilled Trades',
    'GINECOLOGO': 'Technical Education',
    'TEC DIBUJO TECNICO INDUST.': 'Technical Education',
    'TEC ASISTENTE ED.PARVULARIA': 'Technical Education',
    'ASESOR / CONSULTOR': 'Skilled Trades',
    'ARTESANO': 'Skilled Trades',
    'SERVICIO DE ALQUILER DE VEHICULOS': 'Skilled Trades',
    'COREOGRAFO / BAILARIN': 'Skilled Trades',
    'TECNICO ESTADISTICO': 'Technical Education',
    'PANADERO / PASTELERO': 'Skilled Trades',
    'AVICULTOR': 'Skilled Trades',
    'SIQUIATRA': 'University Education',
    'CONTRATISTA': 'Skilled Trades',
    'PINTOR': 'Skilled Trades',
    'REPARTIDOR': 'Skilled Trades',
    'TECNICO EN SONIDO': 'Technical Education',
}
